#!/usr/bin/env bash
# returns a custom header on request so that it configures 
# a brand new Ubuntu machine as required

apt-get -y update
apt-get -y install nginx

sed -i "47i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
echo "Hello World!" | tee /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

service nginx start
