#!/usr/bin/env bash
# This script installs and configures HAproxy on your lb-01 server.

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy

sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sed -i -e '$a\listen balancer\n\tbind :80\n\tbalance roundrobin\n\tserver 147782-web-02 52.91.154.31:80 check\n\tserver 147782-lb-01 100.24.240.147:80 check\n' /etc/haproxy/haproxy.cfg
service haproxy restart
